name: Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install minica
      run: sudo apt-get install -y minica
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      if: success() || failure()
      run: cargo build --verbose --release
    - name: Save build artifact
      if: success() || failure()
      uses: actions/upload-artifact@v3
      with:
        name: syslog-wrapper
        path: target/release/syslog-wrapper
